-- CreateEnum
CREATE TYPE "NoWorkReason" AS ENUM ('TRADER_DIDNT_RESPOND', 'POOR_COMMUNICATION', 'TRADER_DECLINED_JOB', 'TRADER_MISSED_APPOINTMENT', 'QUOTE_OVER_BUDGET', 'BETTER_PRICE_ELSEWHERE', 'WANTED_QUOTE_ONLY', 'JOB_NO_LONGER_NEEDED', 'OTHER');

-- AlterTable
ALTER TABLE "Review" ADD COLUMN     "noWorkReason" "NoWorkReason",
ADD COLUMN     "noWorkReasonText" TEXT,
ADD COLUMN     "workCompletedDate" TIMESTAMP(3),
ADD COLUMN     "wouldRecommendTrader" BOOLEAN;
